import { useEffect, useState, useCallback } from "react";
import axios from "axios";
import jsPDF from "jspdf";
import { QRCodeCanvas } from "qrcode.react";
import "../css/MyBookings.css";

function MyBookings() {
  const [bookings, setBookings] = useState([]);

  const userEmail = localStorage.getItem("email");

  const fetchBookings = useCallback(async () => {
    try {
      const res = await axios.get(
        `http://localhost:5000/api/booking/${userEmail}`
      );

      setBookings(res.data);
    } catch (err) {
      console.log(err);
    }
  }, [userEmail]);

  useEffect(() => {
    fetchBookings();
  }, [fetchBookings]);

  const cancelBooking = async (id) => {
    const confirmCancel = window.confirm(
      "Are you sure you want to cancel this booking?"
    );

    if (!confirmCancel) return;

    try {
      await axios.delete(
        `http://localhost:5000/api/booking/${id}`
      );

      alert("Booking Cancelled Successfully");

      fetchBookings();
    } catch (err) {
      console.log(err);
    }
  };

  const downloadTicket = (booking) => {
    const doc = new jsPDF();

    doc.setDrawColor(128, 0, 0);
    doc.setLineWidth(1);
    doc.rect(10, 10, 190, 277);

    doc.setFillColor(128, 0, 0);
    doc.rect(10, 10, 190, 30, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("DarshanEase", 62, 22);

    doc.setFontSize(12);
    doc.text("Temple Darshan Ticket", 60, 30);

    doc.setTextColor(0, 0, 0);

    doc.setDrawColor(150);
    doc.roundedRect(20, 50, 170, 115, 3, 3);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(13);

    let y = 65;

    doc.text(`Booking ID : ${booking.bookingId}`, 30, y);
    y += 12;

    doc.text(`Temple : ${booking.temple}`, 30, y);
    y += 12;

    doc.text(`Darshan Type : ${booking.darshanType}`, 30, y);
    y += 12;

    doc.text(`Date : ${booking.date}`, 30, y);
    y += 12;

    doc.text(`Time Slot : ${booking.timeSlot}`, 30, y);
    y += 12;

    doc.text(`Persons : ${booking.persons}`, 30, y);
    y += 12;

    doc.text(`Mobile : ${booking.mobile}`, 30, y);
    y += 12;

    doc.text(
      `Amount : ${
        booking.amount === 0
          ? "Free"
          : `Rs. ${booking.amount}`
      }`,
      30,
      y
    );
    y += 12;

    doc.text(`Status : ${booking.status}`, 30, y);

    doc.setDrawColor(128, 0, 0);
    doc.line(20, 185, 190, 185);

    doc.setFontSize(11);
    doc.text(
      "Please carry a valid ID proof during darshan.",
      20,
      200
    );

    doc.text(
      "Reach the temple 30 minutes before your time slot.",
      20,
      210
    );

    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.text("Have a Blessed Darshan", 52, 235);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("Generated by DarshanEase", 70, 255);

    doc.save(`DarshanEase-${booking.bookingId}.pdf`);
  };

 return (
  <div className="bookings-container">
    <h1>🙏 My Bookings</h1>

    {bookings.length === 0 ? (
      <h2 style={{ textAlign: "center" }}>
        No Bookings Found
      </h2>
    ) : (
      bookings.map((booking) => (
        <div
          className="booking-card"
          key={booking._id}
        >
          <div
      style={{
        background: "#8B0000",
        color: "white",
        padding: "12px",
        borderRadius: "10px",
        marginBottom: "15px",
        textAlign: "center",
        fontWeight: "bold",
        fontSize: "18px",
      }}
    >
      🙏 Darshan Ticket
    </div>

     <h2
  style={{
    color: "#8B0000",
    textAlign: "center",
    fontSize: "34px",
    fontWeight: "bold",
    marginBottom: "15px",
  }}
>     
{booking.image && (
  <img
    src={
      booking.image.startsWith("/uploads")
        ? `http://localhost:5000${booking.image}`
        : booking.image
    }

    alt={booking.temple}
    style={{
  width: "100%",
  height: "260px",
  objectFit: "cover",
  borderRadius: "20px",
  marginBottom: "20px",
  boxShadow: "0 5px 15px rgba(0,0,0,0.2)",
}}
  />
)}
  🛕 {booking.temple}
</h2>
<div
  style={{
    background: "linear-gradient(90deg,#8B0000,#d32f2f)",
    color: "white",
    padding: "12px",
    borderRadius: "12px",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: "22px",
    marginBottom: "15px",
  }}
>
  🙏 Welcome to {booking.temple}
</div>

          <p>
           <span
  style={{
    background: "#8B0000",
    color: "white",
    padding: "5px 10px",
    borderRadius: "8px",
  }}
>
  🎟 {booking.bookingId}
</span>
          </p>
    <div className="booking-details">      
  <p>
    <strong>🙏 Darshan Type:</strong>{" "}
    {booking.darshanType}
  </p>

  <p>
    <strong>📅 Date:</strong> {booking.date}
  </p>

  <p>
    <strong>🕒 Time Slot:</strong>{" "}
    {booking.timeSlot}
  </p>

  <p>
    <strong>👥 Persons:</strong>{" "}
    {booking.persons}
  </p>

  <p>
    <strong>📱 Mobile:</strong>{" "}
    {booking.mobile}
  </p>

  <p>
    <strong>💰 Amount:</strong>{" "}
    {booking.amount === 0
      ? "Free"
      : `₹${booking.amount}`}
  </p>

  <p>
    <strong>📌 Status:</strong>

    <span
      style={{
        background: "green",
        color: "white",
        padding: "5px 12px",
        borderRadius: "20px",
        marginLeft: "10px",
      }}
    >
      {booking.status}
    </span>
  </p>
</div>

          

          <div
  style={{
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: "20px",
    background: "#fff7e6",
    padding: "20px",
    borderRadius: "15px",
    flexWrap: "wrap",
  }}
>
  
  <div style={{ textAlign: "center" }}>
    <QRCodeCanvas
      value={JSON.stringify({
        bookingId: booking.bookingId,
        temple: booking.temple,
        date: booking.date,
        timeSlot: booking.timeSlot,
      })}
      size={120}
    />

    <p
      style={{
        fontSize: "12px",
        marginTop: "8px",
      }}
    >
      Scan for Booking Details
    </p>
  </div>

  <div
    style={{
      display: "flex",
      flexDirection: "column",
      gap: "12px",
    }}
  >
    <button
      onClick={() =>
        downloadTicket(booking)
      }
    >
      📄 Download Ticket
    </button>

    <button
      onClick={() =>
        cancelBooking(booking._id)
      }
    >
      ❌ Cancel Booking
    </button>
  </div>
</div></div>
      ))
    )}
  </div>
);
}

export default MyBookings;